# Generated by Django 5.2 on 2025-04-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('course_number', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('abbreviation', models.CharField(max_length=4)),
                ('year', models.PositiveIntegerField()),
                ('semester', models.CharField(choices=[('Fall', 'Fall'), ('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=10)),
            ],
        ),
    ]
