# Generated by Django 5.2 on 2025-04-10 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='section',
            new_name='section_number',
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(),
        ),
    ]
