# Generated by Django 5.2 on 2025-04-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0004_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentfile',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='course',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='AssignmentFile',
        ),
    ]
