# Generated by Django 5.2 on 2025-04-12 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0005_remove_assignmentfile_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='deadline_date',
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('types', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='assignments/pdfs/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='grader.course')),
            ],
        ),
    ]
