# Generated by Django 5.2 on 2025-04-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0006_remove_course_deadline_date_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
