# Generated by Django 5.2 on 2025-04-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0008_remove_course_deadline_course_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentfile',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='course',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='course',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='AssignmentFile',
        ),
    ]
