# Generated by Django 5.2 on 2025-04-12 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0009_remove_assignmentfile_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='deadline',
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('assignment_type', models.CharField(choices=[('homework', 'Homework'), ('test', 'Test'), ('midterm', 'Midterm'), ('final', 'Final'), ('class-assignment', 'Class Assignment')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='grader.course')),
            ],
        ),
    ]
