# Generated by Django 5.2 on 2025-04-12 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0010_remove_course_deadline_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
