# Generated by Django 5.2 on 2025-04-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0011_course_created_on_course_deadline_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='section_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
